// Builds the "Grab prices" bookmarklet from bookmarklet/grab.js.
//   npm run build:bookmarklet
// Writes public/js/bookmarklet-code.js (used by the app's Copy code button).
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { minify } from 'terser';

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
export const SOURCE_PATH = here('./grab.js');
export const OUTPUT_PATH = here('../public/js/bookmarklet-code.js');

export async function buildBookmarklet() {
  const source = await readFile(SOURCE_PATH, 'utf8');
  const { code } = await minify(source, {
    ecma: 5,
    compress: { passes: 2 },
    mangle: true,
    format: { comments: false, ascii_only: true },
  });
  const url = 'javascript:' + code;
  for (const bad of ['#', '%', '\n']) {
    const at = url.indexOf(bad);
    if (at !== -1) {
      throw new Error(
        `Bookmarklet contains a forbidden character ${JSON.stringify(bad)} near: ` +
          url.slice(Math.max(0, at - 30), at + 30)
      );
    }
  }
  return url;
}

export function moduleSource(url) {
  return (
    '// GENERATED by bookmarklet/build.mjs from bookmarklet/grab.js. Do not edit by hand.\n' +
    `export const BOOKMARKLET = ${JSON.stringify(url)};\n`
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const url = await buildBookmarklet();
  await writeFile(OUTPUT_PATH, moduleSource(url));
  console.log(`Built bookmarklet: ${url.length} characters → public/js/bookmarklet-code.js`);
}
